services:
  - type: web
    name: iseg-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: IS_PROD
        value: true
      - key: DOMAIN
        value: https://bps-iseg-api.onrender.com
