"""add encrypted fields

Revision ID: 9fbf35649030
Revises: dea0549fee82
Create Date: 2025-06-05 09:16:32.430118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbf35649030'
down_revision: Union[str, None] = 'dea0549fee82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote_records', 'hash_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote_records', 'hash_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
