"""add encrypted point fields

Revision ID: dea0549fee82
Revises: 
Create Date: 2025-06-05 09:06:09.233527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea0549fee82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_records', sa.Column('C1_srv_x', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('C1_srv_y', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('C2_srv_x', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('C2_srv_y', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('C1_sec_x', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('C1_sec_y', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('C2_sec_x', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('C2_sec_y', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('sig_x', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('sig_y', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('pub_x', sa.Float(), nullable=True))
    op.add_column('vote_records', sa.Column('pub_y', sa.Float(), nullable=True))
    # op.alter_column('vote_records', 'hash_encrypted',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote_records', 'hash_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('vote_records', 'pub_y')
    op.drop_column('vote_records', 'pub_x')
    op.drop_column('vote_records', 'sig_y')
    op.drop_column('vote_records', 'sig_x')
    op.drop_column('vote_records', 'C2_sec_y')
    op.drop_column('vote_records', 'C2_sec_x')
    op.drop_column('vote_records', 'C1_sec_y')
    op.drop_column('vote_records', 'C1_sec_x')
    op.drop_column('vote_records', 'C2_srv_y')
    op.drop_column('vote_records', 'C2_srv_x')
    op.drop_column('vote_records', 'C1_srv_y')
    op.drop_column('vote_records', 'C1_srv_x')
    # ### end Alembic commands ###
